<?php

declare(strict_types = 1);

namespace Yeod\Modules\Catalog\Infrastructure\Persistence\Eloquent\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * Persistence model for `catalog_products`.
 *
 * This is a database row, not a domain concept: it has no behaviour, it must never
 * leave the Infrastructure layer and it must never define a relation to a table
 * owned by another module.
 *
 * @property string $id
 * @property string $sku
 * @property string $name
 * @property int $price_minor_amount
 * @property string $currency
 * @property bool $active
 * @property \Carbon\CarbonImmutable|null $created_at
 * @property \Carbon\CarbonImmutable|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ProductModel newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ProductModel newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ProductModel query()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ProductModel whereActive($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ProductModel whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ProductModel whereCurrency($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ProductModel whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ProductModel whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ProductModel wherePriceMinorAmount($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ProductModel whereSku($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|ProductModel whereUpdatedAt($value)
 * @mixin \Eloquent
 */
final class ProductModel extends Model
{
    /**
     * Indicates if the IDs are auto incrementing.
     *
     * @var bool
     */
    public $incrementing = false;
    /**
     * The table associated with the model.
     *
     * Module tables are prefixed with the module name so the schema stays readable
     * once a dozen modules share one database.
     *
     * @var string
     */
    protected $table = 'catalog_products';
    /**
     * Identifiers are UUIDs generated by the Domain.
     *
     * @var string
     */
    protected $keyType = 'string';
    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'id',
        'sku',
        'name',
        'price_minor_amount',
        'currency',
        'active',
        'created_at',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'price_minor_amount' => 'integer',
            'active'             => 'boolean',
            'created_at'         => 'immutable_datetime',
            'updated_at'         => 'immutable_datetime',
        ];
    }
}
