<?php

declare(strict_types = 1);

namespace Yeod\Shared\Domain\ValueObject;

use Random\RandomException;
use Yeod\Shared\Domain\Contracts\ValueObjectPrimitive;
use Yeod\Shared\Domain\Exception\InvalidValueObject;

/**
 * RFC 4122 version 4 identifier used as the base class for every aggregate id.
 *
 * Identifiers are generated by the Domain, never by the database, so a new
 * aggregate is fully valid before it is persisted.
 */
readonly class Uuid implements ValueObjectPrimitive
{
    /**
     * @param  string  $value  Already validated lowercase UUID string.
     */
    final private function __construct(public string $value) {}

    /**
     * Generate a new random identifier.
     *
     * @throws RandomException When the platform cannot provide secure randomness.
     */
    public static function generate(): static
    {
        $bytes = random_bytes(16);
        $bytes[6] = chr(ord($bytes[6]) & 0x0F | 0x40);
        $bytes[8] = chr(ord($bytes[8]) & 0x3F | 0x80);

        /** @var string $hex */
        $hex = bin2hex($bytes);

        return new static(vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split($hex, 4)));
    }

    /**
     * Rebuild an identifier from its string representation.
     *
     * @param  string  $value  UUID string, dashes required, case insensitive.
     *
     * @throws InvalidValueObject When the string is not a valid UUID.
     */
    public static function fromString(string $value): static
    {
        $normalized = strtolower(trim($value));

        if (preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/', $normalized) !== 1) {
            throw InvalidValueObject::because(static::class, sprintf('"%s" is not a valid UUID', $value));
        }

        return new static($normalized);
    }

    /**
     * {@inheritDoc}
     *
     * @param  self  $other  Identifier to compare against.
     */
    public function equals(ValueObjectPrimitive $other): bool
    {
        return $other instanceof static && $this->value === $other->value;
    }

    /**
     * {@inheritDoc}
     */
    public function toPrimitive(): string
    {
        return $this->value;
    }

    /**
     * Render the identifier.
     */
    public function __toString(): string
    {
        return $this->value;
    }
}
