<?php

declare(strict_types = 1);

namespace Yeod\Modules\Catalog\Domain\Entity;

use DateTimeImmutable;
use Yeod\Modules\Catalog\Domain\Event\ProductPriceWasChanged;
use Yeod\Modules\Catalog\Domain\Event\ProductWasCreated;
use Yeod\Modules\Catalog\Domain\ValueObject\ProductId;
use Yeod\Modules\Catalog\Domain\ValueObject\Sku;
use Yeod\Shared\Domain\Event\AggregateRoot;
use Yeod\Shared\Domain\Event\RecordsDomainEvents;
use Yeod\Shared\Domain\Exception\CurrencyMismatch;
use Yeod\Shared\Domain\Exception\InvalidValueObject;
use Yeod\Shared\Domain\ValueObject\Money;

/**
 * Product aggregate root: the consistency boundary of a sellable item.
 *
 * The class is pure PHP. It knows nothing about Eloquent, requests or Filament,
 * which is exactly what makes it testable without booting the framework.
 */
final class Product implements AggregateRoot
{
    use RecordsDomainEvents;

    /**
     * Maximum length of a product name.
     */
    private const int MAX_NAME_LENGTH = 255;

    /**
     * @param  ProductId  $id  Identity of the product.
     * @param  Sku  $sku  Business identifier, immutable once assigned.
     * @param  string  $name  Display name.
     * @param  Money  $price  Current selling price.
     * @param  bool  $active  Whether the product may be sold.
     * @param  DateTimeImmutable  $createdAt  Creation moment in UTC.
     */
    private function __construct(
        private readonly ProductId $id,
        private readonly Sku $sku,
        private string $name,
        private Money $price,
        private bool $active,
        private readonly DateTimeImmutable $createdAt,
    ) {}

    /**
     * Create a brand-new product and record `catalog.product.created`.
     *
     * @param  ProductId  $id  Identity generated by the repository.
     * @param  Sku  $sku  Unique business identifier.
     * @param  string  $name  Display name.
     * @param  Money  $price  Initial price, must not be negative.
     * @param  DateTimeImmutable  $now  Current moment, injected through the clock.
     *
     * @throws InvalidValueObject When the name is empty or the price is negative.
     */
    public static function create(
        ProductId $id,
        Sku $sku,
        string $name,
        Money $price,
        DateTimeImmutable $now,
    ): self {
        $product = new self($id, $sku, self::guardName($name), self::guardPrice($price), true, $now);

        $product->recordEvent(
            new ProductWasCreated(
                productId       : $id->value,
                sku             : $sku->value,
                name            : $product->name,
                priceMinorAmount: $price->minorAmount,
                currency        : $price->currency->value,
                occurredAt      : $now,
            )
        );

        return $product;
    }

    /**
     * Validate and normalise a product name.
     *
     * @param  string  $name  Raw name.
     *
     * @throws InvalidValueObject When the name is empty or too long.
     */
    private static function guardName(string $name): string
    {
        $normalized = trim($name);

        if ($normalized === '') {
            throw InvalidValueObject::because(self::class, 'product name must not be empty');
        }

        if (mb_strlen($normalized) > self::MAX_NAME_LENGTH) {
            throw InvalidValueObject::because(
                self::class,
                sprintf('product name must not exceed %d characters', self::MAX_NAME_LENGTH),
            );
        }

        return $normalized;
    }

    /**
     * Validate a price.
     *
     * @param  Money  $price  Price to validate.
     *
     * @throws InvalidValueObject When the price is negative.
     */
    private static function guardPrice(Money $price): Money
    {
        if ($price->isNegative()) {
            throw InvalidValueObject::because(self::class, 'product price must not be negative');
        }

        return $price;
    }

    /**
     * Rehydrate an existing product from storage without recording events.
     *
     * Only repositories may call this factory.
     *
     * @param  ProductId  $id  Stored identity.
     * @param  Sku  $sku  Stored SKU.
     * @param  string  $name  Stored name.
     * @param  Money  $price  Stored price.
     * @param  bool  $active  Stored active flag.
     * @param  DateTimeImmutable  $createdAt  Stored creation moment.
     */
    public static function restore(
        ProductId $id,
        Sku $sku,
        string $name,
        Money $price,
        bool $active,
        DateTimeImmutable $createdAt,
    ): self {
        return new self($id, $sku, $name, $price, $active, $createdAt);
    }

    /**
     * Change the selling price and record `catalog.product.price_changed`.
     *
     * Changing to the very same amount is a no-op and records nothing, which keeps
     * the event stream free of noise.
     *
     * @param  Money  $newPrice  New price in the same currency, must not be negative.
     * @param  DateTimeImmutable  $now  Current moment, injected through the clock.
     *
     * @throws InvalidValueObject When the price is negative.
     * @throws CurrencyMismatch When the currency differs.
     */
    public function changePrice(Money $newPrice, DateTimeImmutable $now): void
    {
        self::guardPrice($newPrice);

        if ($this->price->equals($newPrice)) {
            return;
        }

        $old = $this->price;
        $this->price = $newPrice;

        $this->recordEvent(
            new ProductPriceWasChanged(
                productId     : $this->id->value,
                oldMinorAmount: $old->minorAmount,
                newMinorAmount: $newPrice->minorAmount,
                currency      : $newPrice->currency->value,
                occurredAt    : $now,
            )
        );
    }

    /**
     * Rename the product.
     *
     * @param  string  $name  New display name.
     *
     * @throws InvalidValueObject When the name is empty or too long.
     */
    public function rename(string $name): void
    {
        $this->name = self::guardName($name);
    }

    /**
     * Make the product available for sale.
     */
    public function activate(): void
    {
        $this->active = true;
    }

    /**
     * Withdraw the product from sale without deleting it.
     */
    public function deactivate(): void
    {
        $this->active = false;
    }

    /**
     * Identity of the product.
     */
    public function id(): ProductId
    {
        return $this->id;
    }

    /**
     * Business identifier of the product.
     */
    public function sku(): Sku
    {
        return $this->sku;
    }

    /**
     * Display name of the product.
     */
    public function name(): string
    {
        return $this->name;
    }

    /**
     * Current selling price.
     */
    public function price(): Money
    {
        return $this->price;
    }

    /**
     * Whether the product may be sold.
     */
    public function isActive(): bool
    {
        return $this->active;
    }

    /**
     * Creation moment in UTC.
     */
    public function createdAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }
}
